Домашнее задание к лекции Библиотеки Numpy и scipy
Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [10]:
n=10
np.arange(n-1, -1, -1)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [4]:
np.arange?

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [19]:
sum(sum(np.diag((np.arange(n-1, -1, -1)), k=0)))

45

In [13]:
# тут все кроме диагонали = 0, прото сложил. А как реално только диагональ сложит без циклов ? /
#И вообще циклы работают numpy.ndarray?

Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [22]:
from numpy import linalg

In [24]:
a=np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b=np.array([4, 12, -3])



In [26]:
print(a, b)


[[4 2 1]
 [1 3 0]
 [0 5 4]] [ 4 12 -3]


In [27]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [28]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True